// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface PriceConverter$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "PriceConverter";
  readonly sourceName: "contracts/PriceConverter.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200e2fbc00811fc8627411bccfb28f2bff9854932c07cc3c2f67f3465c477b419364736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212200e2fbc00811fc8627411bccfb28f2bff9854932c07cc3c2f67f3465c477b419364736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/PriceConverter.sol";
  readonly buildInfoId: "solc-0_8_28-4265ba20d1641f724df543f06e109cc32c9accf0";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["PriceConverter"]: PriceConverter$Type;
    ["contracts/PriceConverter.sol:PriceConverter"]: PriceConverter$Type;
  }
}